<?php
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Pro Manage AI - Connect Ideas with Investors</title>
    <link rel="stylesheet" href="assets/templatemo-prism-flux.css">
<!-- 

TemplateMo 600 Prism Flux

https://templatemo.com/tm-600-prism-flux

-->
</head>
<body>
    <!-- Loading Screen -->
    <div class="loader" id="loader">
        <div class="loader-content">
            <div class="loader-prism">
                <div class="prism-face"></div>
                <div class="prism-face"></div>
                <div class="prism-face"></div>
            </div>
            <div style="color: var(--accent-purple); font-size: 18px; text-transform: uppercase; letter-spacing: 3px;">Refracting Reality...</div>
        </div>
    </div>

    <!-- Navigation Header -->
    <header class="header" id="header">
        <nav class="nav-container">
            <a href="#home" class="logo">
                <div class="logo-icon">
                    <div class="logo-prism">
                        <div class="prism-shape"></div>
                    </div>
                </div>
                <span class="logo-text">
                    <span class="prism">Pro Manage</span>
                    <span class="flux">AI</span>
                </span>
            </a>
            
            <ul class="nav-menu" id="navMenu">
                <li><a href="#home" class="nav-link active">Home</a></li>
                <li><a href="#innovation" class="nav-link">Innovation</a></li>
                <li><a href="#evenement" class="nav-link">Event</a></li>
                <li><a href="#reclamation" class="nav-link">Reclamation</a></li>
                <li><a href="#actualite" class="nav-link">News</a></li>
                <li><a href="sign-up.php" class="nav-link btn-signup">Sign Up</a></li>
                <li><a href="sign-in.php" class="nav-link btn-signin">Sign In</a></li>
                <li class="profile-dropdown">
                    <a href="#" class="nav-link profile-icon" id="profileDropdownBtn" title="Profile">👤</a>
                    <div class="dropdown-menu" id="profileDropdownMenu">
                        <a href="userprofile.php" class="dropdown-item">
                            <span>👤</span> My Profile
                        </a>
                        <a href="logout.php" class="dropdown-item">
                            <span>🚪</span> Deconnexion
                        </a>
                    </div>
                </li>
            </ul>
            
            <div class="menu-toggle" id="menuToggle">
                <span></span>
                <span></span>
                <span></span>
            </div>
        </nav>
    </header>

    <!-- Hero Section with 3D Carousel -->
    <section class="hero" id="home">
        <div class="carousel-container">
            <div class="carousel" id="carousel">
                <!-- Carousel items will be generated by JavaScript -->
            </div>
            
            <div class="carousel-controls">
                <button class="carousel-btn" id="prevBtn">‹</button>
                <button class="carousel-btn" id="nextBtn">›</button>
            </div>
            
            <div class="carousel-indicators" id="indicators">
                <!-- Indicators will be generated by JavaScript -->
            </div>
        </div>
    </section>

    <!-- About Section -->
    <section class="philosophy-section" id="about">
        <div class="philosophy-container">
            <div class="prism-line"></div>
            
            <h2 class="philosophy-headline">
                Transform Ideas<br>Into Successful Projects
            </h2>
            
            <p class="philosophy-subheading">
                Pro Manage AI is a revolutionary platform that connects visionary innovators with passionate investors. 
                Share your groundbreaking ideas, discover exciting projects, find perfect investment opportunities, 
                and secure valuable internships—all in one intelligent ecosystem.
            </p>
            
            <div class="philosophy-pillars">
                <div class="pillar">
                    <div class="pillar-icon">💡</div>
                    <h3 class="pillar-title">Share Ideas</h3>
                    <p class="pillar-description">
                        Present your innovative concepts to a community of potential investors and collaborators. 
                        Every great business starts with a brilliant idea—share yours and watch it grow.
                    </p>
                </div>
                
                <div class="pillar">
                    <div class="pillar-icon">💰</div>
                    <h3 class="pillar-title">Find Investors</h3>
                    <p class="pillar-description">
                        Connect with investors actively seeking promising projects. Our AI-powered matching system 
                        ensures your ideas reach the right people who can help bring them to life.
                    </p>
                </div>
                
                <div class="pillar">
                    <div class="pillar-icon">🎯</div>
                    <h3 class="pillar-title">Discover Opportunities</h3>
                    <p class="pillar-description">
                        Explore exciting projects to invest in and find valuable internship opportunities. 
                        Build your network and grow your career in the innovation ecosystem.
                    </p>
                </div>
            </div>
            
            <div class="philosophy-particles" id="particles">
                <!-- Particles will be generated by JavaScript -->
            </div>
        </div>
    </section>

    <!-- Stats Section with Content -->
    <section class="stats-section" id="stats">
        <div class="section-header">
            <h2 class="section-title">Platform Impact</h2>
            <p class="section-subtitle">Real-time metrics showcasing our thriving innovation community</p>
        </div>
        
        <div class="stats-grid">
            <div class="stat-card">
                <div class="stat-icon">💡</div>
                <div class="stat-number" data-target="350">0</div>
                <div class="stat-label">Ideas Shared</div>
                <p class="stat-description">Innovative concepts posted by entrepreneurs and visionaries seeking to change the world.</p>
            </div>
            
            <div class="stat-card">
                <div class="stat-icon">💰</div>
                <div class="stat-number" data-target="128">0</div>
                <div class="stat-label">Funded Projects</div>
                <p class="stat-description">Successfully matched ideas with investors, turning dreams into reality with financial backing.</p>
            </div>
            
            <div class="stat-card">
                <div class="stat-icon">🤝</div>
                <div class="stat-number" data-target="200">0</div>
                <div class="stat-label">Active Investors</div>
                <p class="stat-description">Growing community of investors actively seeking and funding promising innovative projects.</p>
            </div>
            
            <div class="stat-card">
                <div class="stat-icon">🎓</div>
                <div class="stat-number" data-target="75">0</div>
                <div class="stat-label">Internships Offered</div>
                <p class="stat-description">Career opportunities created through our platform, connecting talent with innovative companies.</p>
            </div>
        </div>
    </section>

    <!-- Innovation Management Section -->
    <section class="skills-section" id="innovation">
        <div class="skills-container">
            <div class="section-header">
                <h2 class="section-title">Innovation Management</h2>
                <p class="section-subtitle">Discover and manage groundbreaking ideas across various industries</p>
            </div>
            
            <div class="skill-categories">
                <div class="category-tab active" data-category="all">All Ideas</div>
                <div class="category-tab" data-category="frontend">Technology</div>
                <div class="category-tab" data-category="backend">Business</div>
                <div class="category-tab" data-category="cloud">Healthcare</div>
                <div class="category-tab" data-category="emerging">Sustainability</div>
            </div>

            <div class="skills-hexagon-grid" id="skillsGrid">
                <!-- Innovation items will be generated by JavaScript -->
            </div>
        </div>
    </section>

    <!-- Reclamation Section -->
    <section class="contact-section" id="reclamation">
        <div class="section-header">
            <h2 class="section-title">Submit a Reclamation</h2>
            <p class="section-subtitle">Have a concern or feedback? We're here to help and improve.</p>
        </div>
        
        <div class="contact-container">
            <div class="contact-info">
                <a href="mailto:support@promanageai.com" class="info-item">
                    <div class="info-icon">📧</div>
                    <div class="info-text">
                        <h4>Email Support</h4>
                        <p>support@promanageai.com</p>
                    </div>
                </a>
                
                <a href="tel:+15551234567" class="info-item">
                    <div class="info-icon">📱</div>
                    <div class="info-text">
                        <h4>Phone Support</h4>
                        <p>+1 (555) 123-4567</p>
                    </div>
                </a>
                
                <div class="info-item">
                    <div class="info-icon">⏰</div>
                    <div class="info-text">
                        <h4>Response Time</h4>
                        <p>Within 24-48 hours</p>
                    </div>
                </div>
                
                <div class="info-item">
                    <div class="info-icon">💬</div>
                    <div class="info-text">
                        <h4>Live Chat</h4>
                        <p>Available Mon-Fri 9AM-6PM</p>
                    </div>
                </div>
            </div>
            
            <form class="contact-form" id="contactForm">
                <div class="form-group">
                    <label for="name">Full Name</label>
                    <input type="text" id="name" name="name" required>
                </div>
                
                <div class="form-group">
                    <label for="email">Email Address</label>
                    <input type="email" id="email" name="email" required>
                </div>
                
                <div class="form-group">
                    <label for="subject">Reclamation Type</label>
                    <select id="subject" name="subject" required>
                        <option value="">Select Type</option>
                        <option value="technical">Technical Issue</option>
                        <option value="investment">Investment Concern</option>
                        <option value="idea">Idea Issue</option>
                        <option value="account">Account Problem</option>
                        <option value="other">Other</option>
                    </select>
                </div>
                
                <div class="form-group">
                    <label for="message">Describe Your Concern</label>
                    <textarea id="message" name="message" required placeholder="Please provide detailed information about your reclamation..."></textarea>
                </div>
                
                <button type="submit" class="submit-btn">Submit Reclamation</button>
            </form>
        </div>
    </section>

    <!-- Footer -->
    <footer class="footer">
        <div class="footer-content">
            <div class="footer-brand">
                <div class="footer-logo">
                    <div class="logo-icon">
                        <div class="logo-prism">
                            <div class="prism-shape"></div>
                        </div>
                    </div>
                    <span class="logo-text">
                        <span class="prism">Pro Manage</span>
                        <span class="flux">AI</span>
                    </span>
                </div>
                <p class="footer-description">
                    Connecting innovative ideas with passionate investors. Building the future, one project at a time.
                </p>
                <div class="footer-social">
                    <a href="#" class="social-icon">f</a>
                    <a href="#" class="social-icon">t</a>
                    <a href="#" class="social-icon">in</a>
                    <a href="#" class="social-icon">ig</a>
                </div>
            </div>
            
            <div class="footer-section">
                <h4>Platform</h4>
                <div class="footer-links">
                    <a href="#innovation">Innovation Management</a>
                    <a href="#evenement">Events</a>
                    <a href="#reclamation">Reclamations</a>
                    <a href="#actualite">Latest News</a>
                </div>
            </div>
            
            <div class="footer-section">
                <h4>For Users</h4>
                <div class="footer-links">
                    <a href="#">Share Your Idea</a>
                    <a href="#">Find Investors</a>
                    <a href="#">Browse Projects</a>
                    <a href="#">Internships</a>
                </div>
            </div>
            
            <div class="footer-section">
                <h4>Resources</h4>
                <div class="footer-links">
                    <a href="#">How It Works</a>
                    <a href="#">Success Stories</a>
                    <a href="#">FAQ</a>
                    <a href="#">Contact Support</a>
                </div>
            </div>
        </div>
        
        <div class="footer-bottom">
            <div class="copyright">
                © 2025 Pro Manage AI. All rights reserved.
            </div>
            <div class="footer-credits">
                Empowering Innovation & Investment
            </div>
        </div>
    </footer>
<script src="assets/js/templatemo-prism-scripts.js"></script>
<script>
    // Profile dropdown functionality
    document.addEventListener('DOMContentLoaded', function() {
        const profileBtn = document.getElementById('profileDropdownBtn');
        const dropdownMenu = document.getElementById('profileDropdownMenu');
        
        if (profileBtn && dropdownMenu) {
            profileBtn.addEventListener('click', function(e) {
                e.preventDefault();
                dropdownMenu.classList.toggle('show');
            });
            
            document.addEventListener('click', function(e) {
                if (!profileBtn.contains(e.target) && !dropdownMenu.contains(e.target)) {
                    dropdownMenu.classList.remove('show');
                }
            });
        }
    });
</script>
<style>
    .profile-dropdown { position: relative; }
    .dropdown-menu {
        position: absolute; top: 100%; right: 0;
        background: var(--carbon-dark); border: 1px solid var(--metal-dark);
        border-radius: 10px; padding: 10px 0; min-width: 180px;
        margin-top: 10px; opacity: 0; visibility: hidden;
        transform: translateY(-10px); transition: all 0.3s ease;
        z-index: 1000; box-shadow: 0 10px 30px rgba(0, 0, 0, 0.5);
    }
    .dropdown-menu.show { opacity: 1; visibility: visible; transform: translateY(0); }
    .dropdown-item {
        display: flex; align-items: center; gap: 10px;
        padding: 12px 20px; color: var(--text-primary);
        text-decoration: none; transition: all 0.3s ease;
    }
    .dropdown-item:hover { background: linear-gradient(135deg, var(--accent-purple), var(--accent-cyan)); }
    .dropdown-item span { font-size: 1.2rem; }
</style>
</body>
</html>