<!-- Enhanced Skills Section - Technical Arsenal -->
<section class="skills-section" id="skills">
    <div class="skills-container">
        <div class="section-header">
            <h2 class="section-title">Technical Arsenal</h2>
            <p class="section-subtitle">
                Mastery of cutting-edge technologies and frameworks
            </p>
        </div>

        <div class="skill-categories">
            <div class="category-tab active" data-category="all">All Skills</div>
            <div class="category-tab" data-category="frontend">Frontend</div>
            <div class="category-tab" data-category="backend">Backend</div>
            <div class="category-tab" data-category="cloud">Cloud & DevOps</div>
            <div class="category-tab" data-category="emerging">Emerging Tech</div>
        </div>

        <div class="skills-hexagon-grid" id="skillsGrid">
            <!-- Hexagonal skill items will be generated by JavaScript -->
        </div>
    </div>
</section>